#!/usr/bin/env python

from __future__ import print_function

import os
import sys
import getopt
import re
import datetime
import time
import subprocess
import pipes
import md5
import csv

debug_level = 0
foreground = False
logfile = "%s/.bb-up" % (os.environ['HOME'])

def daemonize():
    pid = os.fork()
    if pid > 0:
        sys.exit(0)
    #os.chdir('/')
    os.setsid()
    os.umask(0)
    for fd in range(0, 1023):
        try:
            os.close(fd)
        except OSError:
            pass
    os.open('/dev/null', os.O_RDWR)
    os.dup2(0, 1)
    os.dup2(0, 2)
    pid = os.fork()
    if pid > 0:
        sys.exit(0)

def logx(level, msg):
    nowstr = datetime.datetime.now().ctime()
    if foreground:
        print("%s: %s: %s" % (nowstr, level, msg))
    else:
        f = open(logfile, "a")
        f.write("%s: %s: %s\n" % (nowstr, level, msg))
        f.close()

def logi(s):
    logx('i', s)

def loge(s):
    logx('e', s)

def md5_file(pathname):
    hasher = md5.new()
    f = open(pathname, "r")
    buf = f.read(64*1024)
    while len(buf) > 0:
        hasher.update(buf)
        buf = f.read(64*1024)
    return hasher.hexdigest()

def urlencode(s):
    s = s.replace(' ', '+')
    # RFC 1738 reserved characters: ";", "/", "?", ":", "@", "=" and "&"
    for c in (';', '/', '?', ':', '@', '=', '&'):
        x = "%%%02X" % ord(c)
        s = s.replace(c, x)
    return s

def make_query(m):
    q = ''
    for k, v in m.iteritems():
        if len(q) > 0:
            q += "&"
        q += "%s=%s" % (k, urlencode(str(v)))
    return q

def put_file(rdir, path):
    #argv = ['/usr/bin/ncftpput', '-m', 'pacman', rdir, path]
    argv = ['ncftpput', '-bb', '-f', '/home/build/pacman', rdir, path]
    subprocess.call(argv)
    processname = 'ncftpbatch'
    tmp = os.popen("ps -Af").read()
    batchid = tmp.count(processname)
    if batchid == 0:
        cmd = "ncftpbatch -d"
        subprocess.call(cmd, shell=True)

def put_file_delta(rdir, newpath, oldpath):
    deltapath = newpath.replace('.zip', '.delta') # XXX

    newfile = os.path.basename(newpath)
    oldfile = os.path.basename(oldpath)
    deltafile = os.path.basename(deltapath)

    # Create delta file
    # XXX
    cmd = "rdiff signature \"%s\" | rdiff delta - \"%s\" \"%s\"" % (oldpath, newpath, deltapath)
    subprocess.call(cmd, shell=True)

    newmd5 = md5_file(newpath)
    oldmd5 = md5_file(oldpath)
    deltamd5 = md5_file(deltapath)

    # Upload delta file
    argv = ['ncftpput', '-m', '-f', '/home/build/pacman', rdir, deltapath]
    #argv = ['/usr/bin/ncftpput', '-bb', 'pacman', rdir, deltapath]
    subprocess.call(argv)
    #processname = 'ncftpbatch'
    #tmp = os.popen("ps -Af").read()
    #batchid = tmp.count(processname)
    #if batchid == 0:
        #cmd = "ncftpbatch -d"
        #subprocess.call(cmd, shell=True)

    # Construct remote file
    rdir2=rdir.replace('public_html/','')
    query = make_query( {
        'action'    : 'mkdelta',
        'basisfile' : "%s/%s" % (rdir2, oldfile),
        'deltafile' : "%s/%s" % (rdir2, deltafile),
        'outputfile': "%s/%s" % (rdir2, newfile),
        'basismd5'  : oldmd5,
        'deltamd5'  : deltamd5,
        'outputmd5' : newmd5 } )
    argv = ['/usr/bin/wget', '-q', '-O', '-',
        '--post-data=%s' % (query),
        'https://s.basketbuild.com/uploads/devs/pacman/mkdelta.php' ]
    child = subprocess.Popen(argv, stdin=None, stdout=subprocess.PIPE, stderr=None)
    out, err = child.communicate()
    rc = False
    if child.returncode == 0:
        for line in out.split("\n"):
            if line == 'mk-delta_result=ok':
                rc = True

    # we are done here, remove the deltafile
    del_r_file(deltafile)

    return rc

def remote_list(ftyp, rdir):
    the_list = []
    cmd = "ncftpls -f /home/build/pacman -1 -i '*%s' ftp://basketbuild.com/./%s/" % (ftyp, rdir)
    r_list = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    for line in iter(r_list.stdout.readline, ''):
        the_list.append(line.rstrip('\n'))
    return the_list

def del_r_file(f_del):
    cmd = "ncftpls -f /home/build/pacman -Z '-W rm %s/%s' ftp://basketbuild.com/./%s/" % (remotedir, f_del, remotedir)
    subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)

def remove_undersized(ftyp):
    cmd = "ncftpls -f /home/build/pacman '-x l *%s' ftp://basketbuild.com/./%s/" % (ftyp, remotedir)
    get_remote_list = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    stdout, stderr = get_remote_list.communicate()
    zip_list = csv.DictReader(stdout.decode('ascii').splitlines(),
                            delimiter=' ', skipinitialspace=True,
                            fieldnames=['permissions', 'type',
                                        'owner', 'group', 'size',
                                        'month', 'date', 'time', 'name'])

    for zip in zip_list:
        if int((zip.get('size'))) < max_zip:
            del_r_file(zip.get('name'))
            logi('%s  deleted ...' % (zip.get('name')))
            if ftyp == 'zip':
                del_r_file('%s.md5sum' % (zip.get('name')))
                logi('%s.md5sum  deleted ...' % (zip.get('name')))

def trim_the_list(ftyp):
    the_list = []
    cmd = "ncftpls -f /home/build/pacman -m '-x l *%s' ftp://basketbuild.com/./%s/" % (ftyp, remotedir)
    get_remote_list = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    stdout, stderr = get_remote_list.communicate()
    f_list = csv.DictReader(stdout.decode('ascii').splitlines(),
                            delimiter=';', skipinitialspace=True,
                            fieldnames=['modify', 'perm',
                                        'size', 'type', 'UNIX.group',
                                        'UNIX.mode', 'UNIX.owner', 'name'])
    for zip in f_list:
        if str(zip.get('name')).endswith('md5sum'):
            continue
        if not str(zip.get('type')) == 'type=file':
            continue
        m_name, m_time = zip.get('modify').split('=', 1)
        the_list.append(m_time + '_' + zip.get('name'))
    the_list = sorted(the_list)
    count = 0
    del_count = len(the_list) - max_n_zip
    if del_count > 0:
        logi('We need to make space...')
        while count < del_count:
            f_date, f_del = the_list[count].split('_', 1)
            del_r_file(f_del)
            del_r_file('%s.md5sum' % (f_del))
            logi('%s  deleted ...' % (f_del))
            count += 1

optargs, argv = getopt.getopt(sys.argv[1:], 'df', ['debug', 'foreground'])
for k, v in optargs:
    if k in ('-d', '--debug'):
        debug_level += 1
    if k in ('-f', '--foreground'):
        foreground = True

if len(argv) != 2:
    print("Usage: bb-up remote-dir local-pathname")
    sys.exit(1)

remotedir = argv[0]
newpath = argv[1]
max_zip = 185000000 # the trigger to indicate the zip is undersized and may be from a broken upload
max_n_zip = 10 #the maximun number of zip files allowed in a nightly folder

# clean remotedir
# remove undersized uploads
logi('Checking for undersized upload file(s)..')
remove_undersized('zip')

# get the list of what is left
logi('Getting lists of remote files...')
r_z_list = remote_list('zip', remotedir)
r_m_list = remote_list('md5sum', remotedir)
r_d_list = remote_list('delta', remotedir)

logi('Cecking for unprocessed delta files...')
if r_d_list:
    logi('Found delta file(s)! Getting rid of it...')
    for rfile in r_d_list:
        del_r_file(rfile)
        logi('%s deleted.' % (rfile))

logi('Checking for incomplete sets...')
for r_z_file in r_z_list:
    if not ('%s.md5sum' % (r_z_file)) in r_m_list:
        logi('%s.md5sum not found' % (r_z_file))
        del_r_file(r_z_list.pop(r_z_list.index(r_z_file)))

for r_m_file in r_m_list:
    if not r_m_file[:-7] in r_z_list:
        logi('%s not found' % (r_m_file[:-7]))
        del_r_file(r_m_list.pop(r_m_list.index(r_m_file)))

# remove old uploads
logi('Checking for excess baggage..')
trim_the_list('zip')

if not os.path.exists(newpath):
    print("No such file %s" % (newpath))
    sys.exit(1)

if not foreground:
    daemonize()

logi("upload %s %s" % (remotedir, newpath))

newfile = os.path.basename(newpath)

m = re.search('\d{8}', newfile)
if m is None:
    logi("no date stamp found in file, fall back to normal upload")
    put_file(remotedir, newpath)
    sys.exit(0)

newdatestr = m.group(0)
newdate = datetime.date(int(newdatestr[0:4]), int(newdatestr[4:6]), int(newdatestr[6:8]))
olddate = newdate - datetime.timedelta(days=1)
olddatestr = "%04d%02d%02d" % (olddate.year, olddate.month, olddate.day)

oldpath = newpath.replace(newdatestr, olddatestr)

# check for oldfile on the bot
if not os.path.exists(oldpath):
    logi("yesterdays build not found on bot, fall back to normal upload")
    put_file(remotedir, newpath)
    sys.exit(0)

# check for oldfile on the server
roldfile = newfile.replace(newdatestr, olddatestr)
cmd = "ncftpls -f /home/build/pacman -1 -i '%s' ftp://basketbuild.com/./%s/" % (roldfile, remotedir)
if not subprocess.call(cmd, shell=True) == 0:
    logi("yesterdays build not found on server, fall back to normal upload")
    put_file(remotedir, newpath)
    sys.exit(0)

logi("attempt to put file via delta")
if not put_file_delta(remotedir, newpath, oldpath):
    logi("put file via delta failed, fall back to normal upload")
    put_file(remotedir, newpath)
    sys.exit(0)
