#!/bin/sh

OTA_URL="http://downloads.pac-rom.com/index.php?build-update=true"
OTA_PASS=`grep "ota_pass" /home/build/.jenkins/config | cut -d'=' -f2`

host="$1"
device="$2"
version="$3"
blid="$4"
dlurl="$5"

#    http://downloads.pac-rom.com/index.php?build-update=true&
#device=$device& 
#dl-url=$dlurl& 
#build-id=$blid& 
#host=$host& 
#version=$version

wget -O /dev/null "$OTA_URL&pass=$OTA_PASS&device=$device&dl-url=$dlurl&build-id=$blid&host=$host&version=$version"
